heat_template_version: 2018-08-31

description: |
  Heat template to deploy a MySQL database instance and a WordPress web instance on Ubuntu
  
parameters:
  image:
    type: string
    label: Image name or ID
    description: Image to be used for server. Please use an Ubuntu operating system based image.
    default: ubuntu-jammy
  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used on the compute instance.
    default: m1.small
  key:
    type: string
    label: Key name
    description: Name of key-pair to be installed on the compute instance.
    default: demo-key-2
  private_network:
    type: string
    label: Private network name or ID
    description: Network to attach server to.
    default: provider
  database_name:
    type: string
    description: Name of the MySQL database for WordPress
    default: wordpress
  database_user:
    type: string
    description: Username for the MySQL user
    default: wordpress
  database_password:
    type: string
    description: Password for the MySQL user
    default: Password123
    
resources:
  web_security_group:
      type: OS::Neutron::SecurityGroup
      properties:
        name: web_server_security_group
        rules:
          - protocol: tcp
            port_range_min: 80
            port_range_max: 80
  web_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: private_network }
      security_groups:
        - { get_resource: web_security_group }
        
  db_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: db_server_security_group
      rules:
        - protocol: tcp
          port_range_min: 3306
          port_range_max: 3306
 
  db_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: private_network }
      security_groups:
        - { get_resource: db_security_group }

  database_instance:
    type: OS::Nova::Server
    properties:
      name: database-instance
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key }
      networks:
        - port: { get_resource: db_port }
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #cloud-config
            runcmd:
              - apt-get update
              - DEBIAN_FRONTEND=noninteractive apt-get install -y mariadb-server php php-curl php-gd php-mbstring php-xml php-xmlrpc php-soap libapache2-mod-php php-mysql net-tools
              - sed -i 's/bind-address.*/bind-address = 0.0.0.0/' /etc/mysql/mariadb.conf.d/50-server.cnf    
              - systemctl restart mysql.service
              - mysql -u root -e "CREATE DATABASE __database_name__;"
              - mysql -u root -e "CREATE USER '__database_user__'@'localhost' IDENTIFIED BY '__database_password__';"
              - mysql -u root -e "CREATE USER '__database_user__'@'%' IDENTIFIED BY '__database_password__';"
              - mysql -u root -e "GRANT ALL PRIVILEGES ON __database_name__.* TO '__database_user__'@'localhost';"
              - mysql -u root -e "GRANT ALL PRIVILEGES ON __database_name__.* TO '__database_user__'@'%';"
              - mysql -u root -e "FLUSH PRIVILEGES;"
          params:
            __database_name__: {get_param: database_name}
            __database_user__: {get_param: database_user}
            __database_password__: {get_param: database_password}


  wordpress_instance:
    type: OS::Nova::Server
    properties:
      name: wordpress-instance
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key }
      networks:
        - port: { get_resource: web_port }        
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #cloud-config
            runcmd:
              - apt-get update
              - DEBIAN_FRONTEND=noninteractive apt-get install -y apache2 php php-curl php-gd php-mbstring php-xml php-xmlrpc php-soap libapache2-mod-php php-mysql mariadb-client-core-10.6 net-tools
              - rm -f /var/www/html/index.html
              - cd /var/www/html
              - wget http://wordpress.org/latest.tar.gz
              - tar -xvzf latest.tar.gz
              - cd wordpress
              - cp /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php
              - chown -R www-data:www-data /var/www/html/wordpress
              - chmod -R 775 /var/www/html/wordpress
              - sed -i "s/database_name_here/$(database_name)/" /var/www/html/wordpress/wp-config.php
              - sed -i "s/username_here/$(database_user)/" /var/www/html/wordpress/wp-config.php
              - sed -i "s/password_here/$(database_password)/" /var/www/html/wordpress/wp-config.php
              - sed -i "s/localhost/$(database_instance-net1-ip)/" /var/www/html/wordpress/wp-config.php
              - systemctl restart apache2.service
          params:
            "$(database_instance-net1-ip)": {get_attr: [database_instance, first_address]}
            "$(database_name)": {get_param: database_name}
            "$(database_user)": {get_param: database_user}
            "$(database_password)": {get_param: database_password}